In [19]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

X, y = load_iris(return_X_y = True)

# Convert data numeric -> category

In [20]:
num_att = X.shape[1]
pivot = np.mean(X, axis= 0)
pivot

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [21]:
X_category = np.full(X.shape, True)

for iteration in range(num_att):
    X_category[:, iteration] = X[:, iteration] > pivot[iteration]

X_category

array([[False,  True, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False,  True, False, False],
 

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X_category, y, test_size=0.2, shuffle=False)
X_train

array([[False,  True, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False,  True, False, False],
 

# Gain of sepal length
more doc in data.feature_names 

In [23]:
dict_sepal_count = collections.Counter(X_train[:, 0])
dict_sepal_count 

Counter({False: 78, True: 42})

In [24]:
num_category.update({"sepal_length": len(dict_sepal_length)})

count_table = np.zeros((num_category["sepal_length"], num_category["decision"]), dtype=int)
count_table
search_index = {}

NameError: name 'num_category' is not defined

In [ ]:
for idx, value in enumerate(X_train[:,0]):
    count_table[""]

In [ ]:
list_dict_all_att = []
for each_attr in X_train.T:
    list_dict_all_att.append(collections.Counter(each_attr))
list_dict_all_att

In [ ]:
load_iris(return_X_y= True)

In [ ]:
root = Node(X_train)

names = df["Price"].unique().tolist()   #find unique values
for each_type of att_names:
     self.child.append(df[df["Price"]==names[0]])
store2 = df[df["Price"]==names[1]]
